package com.liteart.apps.sivanmalai;

/**
 * Created by magudesh on 11/6/17.
 */

public class StringArrays {
    static String[] titles = new String[] {
            "அருணகிரிநாதரின் பாதையில் திருப்புகழில் கூறப்பட்டுள்ள இடங்களுக்கு புனித யாத்திரை",
            "ஆஸ்திரேலியாவில் முருக வழிபாடு",
            "இசை மூலம் முருக வழிபாடு",
            "இலங்கை மலையாக்கப் பகுதி மக்களின் முருக வழிபாடு",
            "இலங்கையில் முருகன் வழிபாடு தொல்பொருள் ஆராய்ச்சியில் புதிய பரிமாணம்",
            "இலங்கையின் காவல் தெய்வங்களான ஸ்கந்த முருகன் மற்றும் கதிர்காமன்",
            "இஸ்லாமிய கதிர்காமம்",
            "உத்தர சுவாமிமலை, தில்லி",
            "ஒர் அரசியல் கதை",
            "ஒரிஸ்ஸா மானிலத்தில் கார்த்திகேய வழிபாடு",
            "கதிர்காமனின் இரண்டு மனைவிகள்",
            "கௌமார சிலைகளின் முக்கியத்துவங்கள்",
            "சங்க இலக்கியங்களில் முருகன் பழங்குடி இன வெறியாட்டு வழிபாடு",
            "சித்தாடி காத்தாயி அம்மன் ஆலய வரலாறு",
            "சீனாவின் மஞ்சுஸ்ரீ மற்றும் கார்திகேயாவின் உருவ அமைப்பின் ஒற்றுமைகள்",
            "சோமாஸ்கந்த மூர்த்தி சிலையின் வடிவமைப்பு",
            "தண்டாயுதபாணியின் சிறப்பு",
            "திருப்பரங்குன்ற வரலாறு",
            "தென் ஆப்ரிக்காவில் தமிழ் மொழியும் முருக வழிபாடும்",
            "தென் இந்தியாவில் ஸ்கந்த வழிபாட்டு மரபு",
            "நூறு ஆண்டுகள் முன்பு வீ. டீ. சுப்பிரமணியப் பிள்ளையால் வெளியிடப்பட்ட திருப்புகழ்",
            "பண்டைக் கால நாணயங்களில் கார்த்திகேயர்",
            "பண்டைய கம்போடியாவில் ஸ்கந்த கார்த்திகேயா",
            "பண்டைய தமிழர்கள் பார்வையில் முருகன்",
            "பண்டைய வட நாட்டில் ஸ்கந்த குமார",
            "பண்டைய ஜாவா தீவில் கார்த்திகேயர்",
            "பழனி மலை ஆலய பாத யாத்திரை கிராமிய பழக்க முறைகள்",
            "பிஜித் தீவில் முருக வழிபாடு",
            "புராணங்களில் ஸ்கந்தர் கதைகள்",
            "புலம் பெயர்ந்த தமிழ் மக்களின் முருக பக்தி",
            "மலேஷியாவில் தை பூசம்",
            "முருகனின் பண்டையக் காலச் சிலை",
            "முருகனின் பல்வேறு தோற்றங்கள்",
            "முருகனின் வடிவமைப்புக்கள்",
            "முருகனும் வள்ளியும்",
            "முருகன் ஆலயங்களில் புனித மரங்கள்",
            "முருகன், சுப்பிரமணிய அல்லது கார்த்திகேயர்",
            "மெல்போர்னில் முருக வழிபாடு",
            "மேற்கு வங்காளத்தில் கார்த்திகேய வழிபாடு",
            "மைலம் முருகன் ஆலயம் புராணக் கதை அதன் வளர்ச்சி",
            "மொரீஷியஸில் முருக வழிபாடு",
            "வல்லக்கோட்டை முருகன் ஆலயம்",
            "வள்ளி எனும் பொங்கி அம்மன் இல்லம்",
            "வள்ளிமலை ஸ்வாமிகளுடன் என் அனுபவம்",
            "வைகாசி விசாகமும் முருகப் பெருமானும்",
            "வை துவ் பூ சா போதிசத்துவ ஸ்கந்தன் போதிசத்துவ ஸ்கந்தன்"
    };
    public static String[] story={
            "அவன் வேடத்தில் அவள் முருகன் வேடத்தில் வேலொடு வள்ளி",
            "சிக்கல் சிங்காரவேலன் வேல் வாங்கும் காட்சி",
            "தைப்பூசம் சங்கத் தமிழில் வேல் வழிபாடு",
            "பழனி முருகனின் சித்திர கதை",
            "முருகன் வேறு, வேல் வேறு அல்ல",
            "திருஷ்டி_படப்போகுதய்யா_எந்தன்_கணவரே",
            "பெருமாள்_திருவடி_சூடி_பேரின்பம்_பெறுவோம்",
            "துன்பமெல்லாம்_தீர்க்கும்_திருச்சிற்றம்பலத்தான்",
            "ஏன்_திறக்கவில்லை_சொர்க்கவாசல்",
            "பிழைத்துப்போக_ஒரு_வழியினைச்_சொல்லி_அருள்வாயாக",
            "ஊழியம்_பார்த்த_ஊழி_முதல்வன்",
            "ஊனுக்கு_ஊனிட்ட_வேடவன்",
            "உடலும்_நீயே_உயிரும்_நீயே",
            "பணிப்பெண்ணான_பட்டத்து_ராணி",
            "மனிதராய்_வந்துதித்த_மாதவன்",
            "கலியுகத்தில்_கடைத்தேற்றும்_கிருஷ்ண_நாமம்",
            "எல்லாம்_இறைவன்_அளித்த_மூலதனம்",
            "தாயினும்_சாலப்_பரிந்தூட்டும்_திருஈங்கோய்மலை_இறைவன்",
            "முக்குளத்தில்_நீராடுவோர்_மகிழ்ச்சி_நிறையப்_பெறுவர்",
            "ராமானுஜருக்கு_சரஸ்வதி_வழங்கிய_விருது",
            "அளவுக்கு_அதிகமாக_ஆசைப்படாதே",
            "வளர்ப்புத் தந்தை_வால்மீகி",
            "இறுதி_மூச்சு_வரை_உன்_பணியே",
            "படகோட்டியும்_பட்டாபிஷேகமும்",
            "அருட்பெருஞ்சோதி_அருட்பெருஞ்சோதி_தனிப்பெருங்கருணை_அருட்பெருஞ்சோதி",
            "நம்முடனேயே_வாழ்கிறார்_ஸ்ரீராமானுஜர்",
            "தீமைக்கும்_நன்மை_செய்"
    };
    public static String[] kanthapuranam={
            "http://kaumaram.com/k_puranam/kp_kandam0.html",
            "http://kaumaram.com/k_puranam/kp_kandam1.html",
            "http://kaumaram.com/k_puranam/kp_kandam2.html",
            "http://kaumaram.com/k_puranam/kp_kandam3.html",
            "http://kaumaram.com/k_puranam/kp_kandam4.html",
            "http://kaumaram.com/k_puranam/kp_kandam5.html",
            "http://kaumaram.com/k_puranam/kp_kandam6.html"
    };

    public static String[] kanthapuranam_titles={
            "கந்த புராணம் : துவக்கம்",
            "உற்பத்தி காண்டம்",
            "அசுரகாண்டம்",
            "மகேந்திர காண்டம்",
            "யுத்த காண்டம்",
            "தேவ காண்டம்",
            "தக்ஷ காண்டம்"
    };
    public static String[] articles_titles={
            "Seven untold and unknown facts about Lord Kartikeya",
            "About Birth of Murugan",
            "Journey to Murugan",
            "About Lord Subrahmanya",
            "Murugan Devotional Guide",
            "History of Murugan from PreHistory to Sangam #1 ",
            "History of Murugan from PreHistory to Sangam #2",
            "History of Murugan from PreHistory to Sangam #3",
            "History of Murugan from PreHistory to Sangam #3",
            "History of Palani Murugan Temple",
            "108 Names & Meanings of Lord Muruga",
            "Murugan Baby Names"
    };
    public static String[] articles={
            "http://ritsin.com/seven-unknown-facts-lord-kartikeya.html/",
            "http://www.palanitemples.com/english/muruga's_birthday.htm",
            "https://www.himalayanacademy.com/media/books/6-muruga-temple-pilgrimage_ei/6-muruga-temple-pilgrimage_ei.pdf",
            "http://www.svtemplenc.org/stories/sivaalayam-pratistha-2014/SixAbodesOfLordSubrahmanya.pdf",
            "http://www.londonsrimurugan.org/pdf1/Muruganbakthi.pdf",
            "https://karkanirka.org/2008/05/11/murugan1-2/",
            "https://karkanirka.org/2008/05/11/murugan2/",
            "https://karkanirka.org/2008/05/11/murugan3/",
            "https://karkanirka.org/2008/05/11/murugan4/",
            "http://oommuruga.blogspot.in/2011/07/history-of-palani-murugan-temple.html",
            "http://www.nriol.com/indianparents/lord-muruga.asp",
            "http://www.indianhindunames.com/names-of-god-murugan-karthik.htm"

    };
    public static String[] tab1_title={
        "முருகனின் ஆறுபடை வீடு",
        "தமிழ் கடவுள் முருகனின் பிரம்மாண்ட வரலாற்றில் சில",
"திருச்செந்தூர் முருகன் பற்றி பிரம்மாண்ட வரலாற்று ரகசியங்கள்",
"மலேசிய முருகன் கோயிலில் மறைந்திருக்கும் மர்மம்",
"பழநி நவபாசான சிலை பற்றிய மறைக்கப்பட்ட உண்மைகள்",
"மிரளவைக்கும் பழநி நவபாசான சிலை ரகசியம் "
    };
    public static String[] tab1_url={
        "https://www.youtube.com/watch?v=RH8bWOHY56Q",
        "https://www.youtube.com/watch?v=nbgGYu27KBU ",
"https://www.youtube.com/watch?v=uFTkqRgOl8k ",
"https://www.youtube.com/watch?v=uY7S4fuUUhE ",
"https://www.youtube.com/watch?v=N9xGZt7WG6I",
"https://www.youtube.com/watch?v=R1RsUNyEctA "
    };
     public static String[] tab2_title={
         "கந்த சஷ்டி கவசம்",
         "10 முருகன் பாடல்கள் | மகாநதி ஷோபனா, டி.எம்.எஸ், வீரமணிதாசன்",
"1008 முருகன் போற்றி | மகாநதி ஷோபனா",
"ஆறுமுக கவசம் அறுபடைவீடு சுப்ரபாதம்",
"ஸ்ரீ சுப்பிரமணிய சஹஸ்ரநாமம்",
"சண்முக கவசம் முழுமையான வரிகள்."
    };
    public static String[] tab2_url={
        "https://www.youtube.com/watch?v=CfXXMZK9grE",
        "https://www.youtube.com/watch?v=MjVPIw-iF0Y",
"https://www.youtube.com/watch?v=yXv0a_piHrk",
"https://www.youtube.com/watch?v=B5mNDclLBvE",
"https://www.youtube.com/watch?v=kbQiseXBYPM ",
"https://www.youtube.com/watch?v=muUVduHtvo4  "
    };
     public static String[] tab3_title={
         "பம்பன் ஸ்வாமிகள் - குமாரஸ்தவம்",
         "ஷண்முக கவசம் ",
"பம்பன் ஸ்வாமிகள் - ஷண்முக நாமாவளி",
"பம்பன் ஸ்வாமிகள் -  தங்க ஆனந்த களிப்பு ",
"பம்பன் ஸ்வாமிகள் - பஞ்சாமிர்த வண்ணம் ",
"பம்பன் ஸ்வாமிகள் -  ஆதரிப்பாரெவர்",
"சரண விண்ணப்பம்",
"ஆனந்த களிப்பு ",
"சமாதான சங்கீதம்",
"ஸ்ரீ கதிர்காம வேலர் வண்ணம்",
"திருப்பழநி",
"மனது",
"அவிரரும்பொன் ",
"கதிரேசன் ",
"வாடா திருமுல்லைவாயில் குஹாபாரர் வண்ணம்",
"அயிலரசு ",
"திருவான்மியூர்  ",
"பெருவேண்டுகோள்  ",
"குந்துகால்  ",
"பிழைபொறுக்க முறையீடு ",
"திருநெல்வேலிக்கோவில் ",
"வேண்டுகோள் ",
"அட்டாட்ட விக்கிரக லீலை ",
"வேற்குழவி வேட்கை ",
"ஆறெழுத்துண்மை ",
"பகை கடிதல்  ",
"திருத்தோத்திரம்  ",
"பிரப்பன்வலசை  ",
"போற்றி விண்ணப்பம் ",
"முதல்வன் புராண முடிப்பு ",
"பெரும்பேறு ",
"சரவணப்பொய்கை திருவிளையாடல்   ",
"திருக்கைலாய திருவிளையாடல்  ",
"எண்ணலங்கார லகரி  ",
"அங்கப்பேறு  ",
"அனவரதபாராயணாஷ்டகம்  ",
"நவவீரர் நவரத்தின கலிவிருத்தம்  ",
"நெஞ்சுப்பத்து   ",
"நவரத்தின மீக்கூற்று  ",
"துக்கரகித பிரார்த்தனை  ",
"சஸ்திர பந்தம் ",
"மயூர பந்தம்  ",
"சிவலோக சுந்தரமாலை   ",
"பொன்மயிற்கண்ணி  ",
"அவனியாசை  ",
"தாசப்பிரகாசம் ",
"பரமப்பிரகாசம்  ",
"திருநிறைந்த சிவம் ",
"திருச்சீரலைவாய்  ",
"திருத்தொடையல்  ",
"பெரியசாமி ",
"தெய்வம்  ",
"அமரர்கோ  ",
"குமாரஸ்தவம் ஷண்முக கவசம்   ",
"பிழைபொறுக்க முறையீடு  ",
"அடியவர்க்கடிமை நாம்  ",
"எழிலார் சுரும்பு  ",
"கருணாகரவேலன்  ",
"திருக்கந்தர் திருப்பல்லாண்டு "

    };
    public static String[] tab3_url={
        "https://www.youtube.com/watch?v=DJ4xLF3yuGc ",
"https://www.youtube.com/watch?v=c2AaZNtO6GI&index=2&list=PLGiI5LniBRiBMkx0BH_mRxrQyc9gMIPVG",
"https://www.youtube.com/watch?v=8jUgEVUcHM8&index=3&list=PLGiI5LniBRiBMkx0BH_mRxrQyc9gMIPVG",
"https://www.youtube.com/watch?v=qSCPadj2pIU&index=4&list=PLGiI5LniBRiBMkx0BH_mRxrQyc9gMIPVG ",
"https://www.youtube.com/watch?v=07kBAboYZd4&list=PLGiI5LniBRiBMkx0BH_mRxrQyc9gMIPVG&index=5 ",
"https://www.youtube.com/watch?v=ygbyQpMzxjY&list=PLGiI5LniBRiBMkx0BH_mRxrQyc9gMIPVG&index=6",
"https://www.youtube.com/watch?v=dFhj4R1EvLI&index=7&list=PLGiI5LniBRiBMkx0BH_mRxrQyc9gMIPVG ",
"https://www.youtube.com/watch?v=WY71rToU2XQ&index=8&list=PLGiI5LniBRiBMkx0BH_mRxrQyc9gMIPVG",
"https://www.youtube.com/watch?v=Pwvuf5Bhg-4&list=PLGiI5LniBRiBMkx0BH_mRxrQyc9gMIPVG&index=9 ",
"https://www.youtube.com/watch?v=Iuzz12YeNOI&index=10&list=PLGiI5LniBRiBMkx0BH_mRxrQyc9gMIPVG ",
"https://www.youtube.com/watch?v=3hJA02jxGE8&index=11&list=PLGiI5LniBRiBMkx0BH_mRxrQyc9gMIPVG",
"https://www.youtube.com/watch?v=xHw8qUwmPnQ&index=12&list=PLGiI5LniBRiBMkx0BH_mRxrQyc9gMIPVG",
"https://www.youtube.com/watch?v=9mGG3lRAPGo&list=PLGiI5LniBRiBMkx0BH_mRxrQyc9gMIPVG&index=13 ",
"https://www.youtube.com/watch?v=FZj4pvahTbs&index=14&list=PLGiI5LniBRiBMkx0BH_mRxrQyc9gMIPVG",
"https://www.youtube.com/watch?v=HAKlrq0pV1I&list=PLGiI5LniBRiBMkx0BH_mRxrQyc9gMIPVG&index=15 ",
"https://www.youtube.com/watch?v=3jQ4x79a6Hs&index=16&list=PLGiI5LniBRiBMkx0BH_mRxrQyc9gMIPVG ",
"https://www.youtube.com/watch?v=OydDHLPHTxw&index=17&list=PLGiI5LniBRiBMkx0BH_mRxrQyc9gMIPVG",
"https://www.youtube.com/watch?v=BvzZl4Q2e-w&index=18&list=PLGiI5LniBRiBMkx0BH_mRxrQyc9gMIPVG",
"https://www.youtube.com/watch?v=A9DgsecRCZc&list=PLGiI5LniBRiBMkx0BH_mRxrQyc9gMIPVG&index=19",
"https://www.youtube.com/watch?v=E8hIgppUBko&list=PLGiI5LniBRiBMkx0BH_mRxrQyc9gMIPVG&index=20",
"https://www.youtube.com/watch?v=Oq_hUJHVrLU&list=PLGiI5LniBRiBMkx0BH_mRxrQyc9gMIPVG&index=21",
"  https://www.youtube.com/watch?v=YAuqMDaIeXw&list=PLGiI5LniBRiBMkx0BH_mRxrQyc9gMIPVG&index=22",
" https://www.youtube.com/watch?v=SNJ_GRgvAC8&index=23&list=PLGiI5LniBRiBMkx0BH_mRxrQyc9gMIPVG",
"https://www.youtube.com/watch?v=un8-VqaHaUg&list=PLGiI5LniBRiBMkx0BH_mRxrQyc9gMIPVG&index=24",
" https://www.youtube.com/watch?v=toidUr3NusE&index=25&list=PLGiI5LniBRiBMkx0BH_mRxrQyc9gMIPVG ",
"https://www.youtube.com/watch?v=xWYjtaX-piY&list=PLGiI5LniBRiBMkx0BH_mRxrQyc9gMIPVG&index=26",
"https://www.youtube.com/watch?v=Hum-qICCdu8&index=27&list=PLGiI5LniBRiBMkx0BH_mRxrQyc9gMIPVG",
" https://www.youtube.com/watch?v=G8XsvAATGGk&index=28&list=PLGiI5LniBRiBMkx0BH_mRxrQyc9gMIPVG ",
"   https://www.youtube.com/watch?v=N6mWDuBI13I&list=PLGiI5LniBRiBMkx0BH_mRxrQyc9gMIPVG&index=29",
" https://www.youtube.com/watch?v=DxEjIv3bfRA&index=30&list=PLGiI5LniBRiBMkx0BH_mRxrQyc9gMIPVG ",
"https://www.youtube.com/watch?v=NoWvDlhI9NE&list=PLGiI5LniBRiBMkx0BH_mRxrQyc9gMIPVG&index=31",
" https://www.youtube.com/watch?v=dinYmAKYw1w&list=PLGiI5LniBRiBMkx0BH_mRxrQyc9gMIPVG&index=32",
"   https://www.youtube.com/watch?v=lVnkXlAasoY&list=PLGiI5LniBRiBMkx0BH_mRxrQyc9gMIPVG&index=33 ",
" https://www.youtube.com/watch?v=hWAt8gag3p0&index=34&list=PLGiI5LniBRiBMkx0BH_mRxrQyc9gMIPVG ",
" https://www.youtube.com/watch?v=pG_7YfM_r_c&index=35&list=PLGiI5LniBRiBMkx0BH_mRxrQyc9gMIPVG",
" https://www.youtube.com/watch?v=YKlHTPOeVSA&index=36&list=PLGiI5LniBRiBMkx0BH_mRxrQyc9gMIPVG ",
"https://www.youtube.com/watch?v=-cHtUZxlDeY&list=PLGiI5LniBRiBMkx0BH_mRxrQyc9gMIPVG&index=37",
" https://www.youtube.com/watch?v=vFhP4k11Jxc&index=38&list=PLGiI5LniBRiBMkx0BH_mRxrQyc9gMIPVG ",
"  https://www.youtube.com/watch?v=0HggdifkDGg&list=PLGiI5LniBRiBMkx0BH_mRxrQyc9gMIPVG&index=39",
"  https://www.youtube.com/watch?v=syli2QjLtCE&list=PLGiI5LniBRiBMkx0BH_mRxrQyc9gMIPVG&index=40 ",
"  https://www.youtube.com/watch?v=3hJ0MYPKSBQ&list=PLGiI5LniBRiBMkx0BH_mRxrQyc9gMIPVG&index=41 ",
"  https://www.youtube.com/watch?v=gCtK30lY6zA&index=42&list=PLGiI5LniBRiBMkx0BH_mRxrQyc9gMIPVG ",
"   https://www.youtube.com/watch?v=JOdGa3Txdz4&index=43&list=PLGiI5LniBRiBMkx0BH_mRxrQyc9gMIPVG",
"  https://www.youtube.com/watch?v=JC2sSKOGYKc&list=PLGiI5LniBRiBMkx0BH_mRxrQyc9gMIPVG&index=44",
"  https://www.youtube.com/watch?v=p_EadoKgmbk&list=PLGiI5LniBRiBMkx0BH_mRxrQyc9gMIPVG&index=45",
"https://www.youtube.com/watch?v=Uw7mRnWbgkA&list=PLGiI5LniBRiBMkx0BH_mRxrQyc9gMIPVG&index=46",
"  https://www.youtube.com/watch?v=kh3nRbk0pls&list=PLGiI5LniBRiBMkx0BH_mRxrQyc9gMIPVG&index=47",
"  https://www.youtube.com/watch?v=y42LGNfjzvo&list=PLGiI5LniBRiBMkx0BH_mRxrQyc9gMIPVG&index=48 ",
"   https://www.youtube.com/watch?v=bGaW0Q2N1TQ&list=PLGiI5LniBRiBMkx0BH_mRxrQyc9gMIPVG&index=49",
"   https://www.youtube.com/watch?v=mW8arLDYQFc&index=50&list=PLGiI5LniBRiBMkx0BH_mRxrQyc9gMIPVG",
"https://www.youtube.com/watch?v=Uw7mRnWbgkA&index=46&list=PLGiI5LniBRiBMkx0BH_mRxrQyc9gMIPVG",
"https://www.youtube.com/watch?v=RmNcjwA3B2A&list=PLGiI5LniBRiBMkx0BH_mRxrQyc9gMIPVG&index=52 ",
" https://www.youtube.com/watch?v=HJTFTDly_D4&list=PLGiI5LniBRiBMkx0BH_mRxrQyc9gMIPVG&index=53 ",
" https://www.youtube.com/watch?v=JEi5nsIFaPc&index=54&list=PLGiI5LniBRiBMkx0BH_mRxrQyc9gMIPVG ",
"  https://www.youtube.com/watch?v=l96drnkGcqk&index=55&list=PLGiI5LniBRiBMkx0BH_mRxrQyc9gMIPVG",
"   https://www.youtube.com/watch?v=ayXYluPK4aU&list=PLGiI5LniBRiBMkx0BH_mRxrQyc9gMIPVG&index=56 ",
" https://www.youtube.com/watch?v=k5A1f8RgT9k&index=57&list=PLGiI5LniBRiBMkx0BH_mRxrQyc9gMIPVG   ",
"   https://www.youtube.com/watch?v=8ZtQnditBYo&index=58&list=PLGiI5LniBRiBMkx0BH_mRxrQyc9gMIPVG ",
"https://www.youtube.com/watch?v=_zi11xZHFuI&index=59&list=PLGiI5LniBRiBMkx0BH_mRxrQyc9gMIPVG"

    };
}
